# Generated by Django 4.0.2 on 2022-04-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('describtion', models.TextField()),
                ('picture', models.ImageField(upload_to='media/% Y/% m/')),
                ('price', models.FloatField(max_length=10)),
                ('stock', models.IntegerField(max_length=3)),
            ],
        ),
    ]
